<?php
/**
 * Copyright © Volodymyr Klymenko. All rights reserved.
 * See LICENSE.txt for license details.
 */
/** @var $block \Sangria\BackendVoice\Block\GlobalVoice */
?>
<div class="voice-global" data-mage-init='{"globalSearch": {}}'>
    <form action="#" id="form-voice">
        <div class="voice-global-field">
            <div class="voice-global-loader"></div>
            <label class="voice-global-label" for="voice-global" id="recordButton"></label>
            <label class="voice-global-phrase" style="
                width: max-content;
                display: block;
                float: right;
                margin: 7px;
                padding: 0 30px 0 0;"></label>
            <button
                type="submit"
                class="voice-global-action"
                title="<?= $block->escapeHtmlAttr(__('Voice')) ?>"
            ></button>
        </div>
    </form>
</div>
<div id="voice-modal">
    <div id="voice-modal-content" class="voice-modal-content"></div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Sangria_BackendVoice/js/voice": {
                "url": "<?= /* @noEscape */ $block->getUrl('adminhtml/voice'); ?>"
            }
        }
    }
</script>
